### ISSUE TITLE
Didn't work for me, followed the steps, getting   playwright._impl._api_types.Error: value: expected string, got undefined

### ISSUE THREAD

**Issue by altryne** [taranjeet/chatgpt-api#1]
`playwright._impl._api_types.Error: value: expected string, got undefined`

**Comment by altryne** [comment]
It's because it's expecting the input to be q (at least in daniels version) and your example sends it via -D param in curl

**Comment by taranjeet** [comment]
Updated doc 2aeedd83a1e05a557afd1b212e9b85bc442a74b7
