### ISSUE TITLE
I can't get passed the verify you are a human bottom. Any suggestions?

### ISSUE THREAD

**Issue by tijgersoftware** [taranjeet/chatgpt-api#23]

**Comment by hangzhi22** [comment]
I have the same issue. Cannot prompt the captcher of Cloudfare correctly in chromium.

**Comment by watzapnet** [comment]
Same here.. Devs are writing code but generally no answers for the issues. Strange.

**Comment by peterw** [comment]
any work arounds?

**Comment by mefengl** [comment]
”puppeteer is an optional peer dependency used to automate `bypassing the Cloudflare protections via getOpenAIAuth`. The main API wrapper uses fetch directly.” from https://github.com/transitive-bullshit/chatgpt-api#install

I am trying it, by the way, see https://github.com/mefengl/play-chatgpt

**Comment by adalbertobrant** [comment]
from playwright.sync_api import sync_playwright

PROFILE_DIR = "/tmp/playwright" if '--profile' not in sys.argv else sys.argv[sys.argv.index('--profile') + 1]
PORT = 5001 if '--port' not in sys.argv else int(sys.argv[sys.argv.index('--port') + 1])
APP = flask.Flask(__name__)
PLAY = sync_playwright().start()
BROWSER = PLAY.firefox.launch_persistent_context(
    user_data_dir=PROFILE_DIR,
    headless=False,
    java_script_enabled=True,
)
PAGE = BROWSER.new_page()

**Comment by adalbertobrant** [comment]
`from playwright.sync_api import sync_playwright

PROFILE_DIR = "/tmp/playwright" if '--profile' not in sys.argv else sys.argv[sys.argv.index('--profile') + 1]
PORT = 5001 if '--port' not in sys.argv else int(sys.argv[sys.argv.index('--port') + 1])
APP = flask.Flask(__name__)
PLAY = sync_playwright().start()
BROWSER = PLAY.firefox.launch_persistent_context(
    user_data_dir=PROFILE_DIR,
    headless=False,
    java_script_enabled=True,
)
PAGE = BROWSER.new_page()`

**Comment by adalbertobrant** [comment]
Change in server.py to firefox like this :
`
from playwright.sync_api import sync_playwright

PROFILE_DIR = "/tmp/playwright" if '--profile' not in sys.argv else sys.argv[sys.argv.index('--profile') + 1]
PORT = 5001 if '--port' not in sys.argv else int(sys.argv[sys.argv.index('--port') + 1])
APP = flask.Flask(__name__)
PLAY = sync_playwright().start()
BROWSER = PLAY.firefox.launch_persistent_context(
    user_data_dir=PROFILE_DIR,
    headless=False,
    java_script_enabled=True,
)
PAGE = BROWSER.new_page()
`

**Comment by Q22aprildd** [comment]
hi sir sorry i am very first time to join in the github family that's why i am always research sorry... maybe i am overwhelmed person...

**Comment by navincodesalot** [comment]
ji sir

**Comment by nettles-sync** [comment]
Cloudflare bot verification has broken this script. Not functional
